services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "5000:5000" # Expose API port to host
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - appesso-network

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./website/.env
    ports:
      - "3000:3000" # Expose website port to host
    volumes:
      - ./website:/app
      - /app/node_modules
    networks:
      - appesso-network

  studio:
    build:
      context: ./api
    restart: always
    depends_on:
      - api
    command: npx prisma studio --hostname 0.0.0.0 --port 5555
    env_file:
      - ./api/.env
    ports:
      - "5555:5555" # Expose Prisma Studio port to host
    networks:
      - appesso-network

networks:
  appesso-network:
    driver: bridge
