# docker-compose.prod.yml
version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appesso-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - db
    env_file:
      - ./api/.env
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - appesso-network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - appesso-network

networks:
  appesso-network:
    driver: bridge

volumes:
  db-data: 